title = "Let's Talk Python book"
baseURL = "https://letstalkpython.com"
languageCode = "en-us"
theme = "hugo-theme-relearn"

resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

#[module]
#[[module.imports]]
#path = "github.com/McShelby/hugo-theme-relearn"

[author]
name = "Pavel Anni"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "Additional content for the book"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3
themeVariant = "green"
disableNextPrev = true

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/PavelAnni"


[security]
enableInlineShortcodes = false

[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GEM_PATH)$']

[security.funcs]
getenv = ['^HUGO_']

[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']
